### ISSUE TITLE
addholo leaderboard

### ISSUE THREAD

**Issue by Hrupec** [ScreamingSandals/SimpleGuiFormat#7]
Witam, proszę o pomoc.

[16:19:43 INFO]: Hrupec issued server command: /bw addholo leaderboard
[16:19:43 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'bw' in plugin BedWars v0.2.15
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Paper-503]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-503]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Paper-503]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2028) ~[patched_1.16.5.jar:git-Paper-503]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1838) ~[patched_1.16.5.jar:git-Paper-503]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1791) ~[patched_1.16.5.jar:git-Paper-503]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.5.jar:git-Paper-503]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.5.jar:git-Paper-503]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-503]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-503]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-503]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-503]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-503]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1138) ~[patched_1.16.5.jar:git-Paper-503]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1131) ~[patched_1.16.5.jar:git-Paper-503]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-503]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1092) ~[patched_1.16.5.jar:git-Paper-503]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1006) ~[patched_1.16.5.jar:git-Paper-503]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Paper-503]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
	at java.lang.String.replace(String.java:2240) ~[?:1.8.0_201]
	at org.screamingsandals.bedwars.holograms.LeaderboardHolograms.lambda$updateHologram$3(LeaderboardHolograms.java:130) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_201]
	at org.screamingsandals.bedwars.holograms.LeaderboardHolograms.updateHologram(LeaderboardHolograms.java:129) ~[?:?]
	at org.screamingsandals.bedwars.holograms.LeaderboardHolograms.lambda$updateHolograms$2(LeaderboardHolograms.java:113) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_201]
	at org.screamingsandals.bedwars.holograms.LeaderboardHolograms.updateHolograms(LeaderboardHolograms.java:108) ~[?:?]
	at org.screamingsandals.bedwars.holograms.LeaderboardHolograms.updateEntries(LeaderboardHolograms.java:43) ~[?:?]
	at org.screamingsandals.bedwars.holograms.LeaderboardHolograms.addHologramLocation(LeaderboardHolograms.java:31) ~[?:?]
	at org.screamingsandals.bedwars.commands.AddholoCommand.execute(AddholoCommand.java:25) ~[?:?]
	at org.screamingsandals.bedwars.commands.BwCommandsExecutor.onCommand(BwCommandsExecutor.java:72) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-503]
	... 19 more

**Comment by zlataovce** [comment]
Not related to SimpleInventories.
